### PR TITLE
Done Anthony Catalfo

### PR DESCRIPTION
**Pull request by AnthonyCatalfo**

### CODE REVIEW

**Comment by wlharvey4** [comment]
Tony,
Your work is perfection itself.  There is nothing to criticize whatsoever.  Awesome job.  Please consider doing the stretch, if for no other reason than to demonstrate your master of the MVC paradigm.

Wesley

**Comment by mixelpixel** [comment]
@AnthonyCatalfo where are your answers to the questions in the readme.md file?

**Comment by mixelpixel** [comment]
@wlharvey4 "perfection itself"? 🤔 No.

@AnthonyCatalfo You need to get in the habit of making git commit messages more often. This will help you to be a better programmer; better at time  management; better at pair programming; better at analyzing problems; better at reading code; et cetera. Your work here in building the server is solid, however, I expect MUCH better from you in terms of the overall picture, i.e. ANSWER the questions & COMMIT your work often with meaningful git commit messages.

**Comment by decagondev** [comment]
## Overview
Anthony, your overall code base is looking good, and your understanding of node seems to be evident. but as mixelpixel pointed out there is an importance to the regularity and granularity of commits. 

## Breakdown
- GREAT work on the code base and quality of workflow in the code
- OK work on the management of your code base
- NOT SO GOOD commit messages and granularity. and the lack of any content in your answers file.

## Conclusions
your code is good and so is your general understanding of node, that being said you seem to have shown a lack of soft skills in this project. The project is quite old so i am presuming that your newer projects are all using better commits and general attention to the project specs. I hope to see more from your projects as you have a lot of potential Anthony

**Pull request closed without merging**
